version: '3.1'

volumes: #docker will mount the volume into /var/lib/docker/volumes
  grafana-volume:
  postgres-data:
  sonarqube:

services:

  dbpostgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:8.2.0
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    user: '472'
    links:
      - "dbpostgres"

  sonarqube:
    image: sonarqube:community
    depends_on:
      - dbpostgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://dbpostgres:5432/pgdb
      SONAR_JDBC_USERNAME: pguser
      SONAR_JDBC_PASSWORD: pguser
    volumes:
      - sonarqube:/opt/sonarqube
    ports:
      - "9000:9000"
    links:
      - "dbpostgres"

